SMODS.Blind:take_ownership('small', { dollars = 30, mult = 10, pos = { x = 0, y = 0 }})
SMODS.Blind:take_ownership('big', { dollars = 40, mult = 15, pos = { x = 0, y = 1 }})

SMODS.Blind:take_ownership('ox', { dollars = 50, mult = 20, pos = { x = 0, y = 2 }, boss = { min = 6 },})
SMODS.Blind:take_ownership('house', { dollars = 50, mult = 20, pos = { x = 0, y = 3 }, boss = { min = 2 },})
SMODS.Blind:take_ownership('club', { dollars = 50, mult = 20, pos = { x = 0, y = 4 }, boss = { min = 1 }, debuff = { suit = "Clubs" },})
SMODS.Blind:take_ownership('fish', { dollars = 50, mult = 20, pos = { x = 0, y = 5 }, boss = { min = 2 },})
SMODS.Blind:take_ownership('window', { dollars = 50, mult = 20, pos = { x = 0, y = 6 }, boss = { min = 1 }, debuff = { suit = "Diamonds" },})
SMODS.Blind:take_ownership('hook', { dollars = 50, mult = 20, pos = { x = 0, y = 7 }, boss = { min = 1 },})
SMODS.Blind:take_ownership('manacle', { dollars = 50, mult = 20, pos = { x = 0, y = 8 }, boss = { min = 1 },})
SMODS.Blind:take_ownership('wall', { dollars = 50, mult = 40, pos = { x = 0, y = 9 }, boss = { min = 2 },})
SMODS.Blind:take_ownership('wheel', { dollars = 50, mult = 20, pos = { x = 0, y = 10 }, boss = { min = 2 },})
SMODS.Blind:take_ownership('arm', { dollars = 50, mult = 20, pos = { x = 0, y = 11 }, boss = { min = 2 },})
SMODS.Blind:take_ownership('psychic', { dollars = 50, mult = 20, pos = { x = 0, y = 12 }, boss = { min = 1 }, debuff = { h_size_ge = 5 },})
SMODS.Blind:take_ownership('goad', { dollars = 50, mult = 20, pos = { x = 0, y = 13 }, boss = { min = 1 }, debuff = { suit = "Spades" },})
SMODS.Blind:take_ownership('water', { dollars = 50, mult = 20, pos = { x = 0, y = 14 }, boss = { min = 2 }})
SMODS.Blind:take_ownership('serpent', { dollars = 50, mult = 20, pos = { x = 0, y = 15 }, boss = { min = 5 }})
SMODS.Blind:take_ownership('pillar', { dollars = 50, mult = 20, pos = { x = 0, y = 16 }, boss = { min = 1 }})
SMODS.Blind:take_ownership('eye', { dollars = 50, mult = 20, pos = { x = 0, y = 17}, boss = { min = 3 }})
SMODS.Blind:take_ownership('mouth', { dollars = 50, mult = 20, pos = { x = 0, y = 18 }, boss = { min = 2 }})
SMODS.Blind:take_ownership('plant', { dollars = 50, mult = 20, pos = { x = 0, y = 19 }, boss = { min = 4 }})
SMODS.Blind:take_ownership('needle', { dollars = 50, mult = 10, pos = { x = 0, y = 20 }, boss = { min = 2 }})
SMODS.Blind:take_ownership('head', { dollars = 50, mult = 20, pos = { x = 0, y = 21 }, boss = { min = 1 }, debuff = { suit = "Hearts" },})
SMODS.Blind:take_ownership('tooth', { dollars = 50, mult = 10, pos = { x = 0, y = 22 }, boss = { min = 3 }})
SMODS.Blind:take_ownership('mark', { dollars = 50, mult = 20, pos = { x = 0, y = 23 }, boss = { min = 2 }})
SMODS.Blind:take_ownership('flint', { dollars = 50, mult = 20, pos = { x = 0, y = 24 }, boss = { min = 2 }})
SMODS.Blind:take_ownership('final_heart', { dollars = 80, mult = 20, pos = { x = 0, y = 25 }, boss = { showdown = true }, })
SMODS.Blind:take_ownership('final_bell', { dollars = 80, mult = 20, pos = { x = 0, y = 26 }, boss = { showdown = true }, })
SMODS.Blind:take_ownership('final_acorn', { dollars = 80, mult = 20, pos = { x = 0, y = 27 }, boss = { showdown = true }, })
SMODS.Blind:take_ownership('final_leaf', { dollars = 80, mult = 20, pos = { x = 0, y = 28 }, boss = { showdown = true }, })
SMODS.Blind:take_ownership('final_vessel', { dollars = 80, mult = 60, pos = { x = 0, y = 29 }, boss = { showdown = true }, })